# Generated by Django 4.1.5 on 2023-03-27 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Tire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=200, null=True)),
                ("line", models.CharField(max_length=200, null=True)),
                ("size", models.CharField(max_length=200, null=True)),
                ("mileage_rating", models.CharField(max_length=40, null=True)),
                ("base_price", models.FloatField(null=True)),
                (
                    "tread_pattern",
                    models.CharField(
                        choices=[
                            ("Street Tread", "Street Tread"),
                            ("All-Terrain", "All-Terrain"),
                            ("Mud Terrain", "Mud-Terrain"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "condition",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True
                    ),
                ),
                (
                    "adjusted_price",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("quantity", models.IntegerField()),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="app.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="app.store",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
