# Generated by Django 4.1.5 on 2023-03-28 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_tire_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="OrderQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_of_tires", models.IntegerField()),
                ("tire", models.ManyToManyField(to="app.tire")),
            ],
        ),
        migrations.AddField(
            model_name="outvoice",
            name="order_quantity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_quantity",
                to="app.orderquantity",
            ),
        ),
    ]
