# Generated by Django 4.1.5 on 2023-03-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_outvoice_alter_tire_quantity_tire_outvoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=200)),
                ("indv_cost", models.FloatField(null=True)),
                ("total_cost", models.FloatField(null=True)),
                ("date_sold", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="outvoice",
            name="total_cost",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="outvoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tire_set",
                to="app.outvoice",
            ),
        ),
        migrations.AddField(
            model_name="tire",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tire_set",
                to="app.invoice",
            ),
        ),
    ]
