# Generated by Django 4.1.5 on 2023-03-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_tire_quantity_orderquantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderquantity",
            name="num_of_tires",
            field=models.IntegerField(null=True),
        ),
    ]
