# Generated by Django 4.1.5 on 2023-03-28 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_orderquantity_num_of_tires"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outvoice",
            name="order_quantity",
        ),
        migrations.AddField(
            model_name="orderquantity",
            name="outvoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_quantity",
                to="app.outvoice",
            ),
        ),
        migrations.RemoveField(
            model_name="orderquantity",
            name="tire",
        ),
        migrations.AddField(
            model_name="orderquantity",
            name="tire",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.tire",
            ),
        ),
    ]
