# Generated by Django 4.1.5 on 2023-03-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_tire_invoice_remove_tire_outvoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tire",
            name="order_qty",
            field=models.IntegerField(null=True),
        ),
    ]
