# Generated by Django 4.1.5 on 2023-03-28 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_outvoice_order_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderquantity",
            name="tire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.tire",
            ),
        ),
    ]
