# Generated by Django 4.1.5 on 2023-03-28 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_orderquantity_tire"),
    ]

    operations = [
        migrations.AddField(
            model_name="outvoice",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outvoices",
                to="app.store",
            ),
        ),
    ]
