# Generated by Django 4.1.5 on 2023-03-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_outvoice_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="outvoice",
            name="is_finalized",
            field=models.BooleanField(default=False),
        ),
    ]
